
export EDITOR=nvim
export HISTIGNORE="pwd:ls:cd" # Remove history data we don't want to see

# Plugins
source ~/.zsh/init.sh
source ~/.zsh/zsh-autosuggestions.zsh
for FILE in $(find ~/.zsh -not -name "init.sh" -name "*.sh"); do
  source $FILE
done

# # Turn off MacOS intercepting Ctrl + Left/Right.
# # see https://superuser.com/a/1522945
# # TODO: is there a way to make this only get added to mac zshrcs?
# # bindkey '^[[1;5D' backward-word
# # bindkey '^[[1;5C' forward-word

alias diff=difft
alias nv='nvim .'
alias cht='cht\.sh'
alias ls=eza
alias du=dust
alias cat=bat
alias k=kubectl
alias i=istioctl
