name: default
root: ~/

attach: false

windows:
  - terminal:
      layout: main-vertical
  - task:
      root: ~/notes
      panes:
        - 'task'
  - notes:
      root: ~/notes
      panes: 
        - 'nvim .'
