#!/bin/sh -e

GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

FLAKE="macos"
SYSTEM="darwinConfigurations.$FLAKE.system"

echo "${YELLOW}Starting build...${NC}"
nix --experimental-features 'nix-command flakes' build .#$SYSTEM

echo "${YELLOW}Switching to new generation...${NC}"
./result/sw/bin/darwin-rebuild switch --flake .#$FLAKE

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
